### ISSUE TITLE
Nc: crash (linux only?)

### ISSUE THREAD

**Issue by JeanMax** [jon-finkel/corewar#18]
que sous linux a priori:

```
./corewar.san -g test/ressources/ctrl_cor/zork.cor

AddressSanitizer:DEADLYSIGNAL
=================================================================
==27669==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000074 (pc 0x7ff1fe72f188 bp 0x5639f59ca8c0 sp 0x7fff2ea87ed0 T0)
==27669==The signal is caused by a READ memory access.
==27669==Hint: address points to the zero page.
    #0 0x7ff1fe72f187 in _nc_printf_string_sp (/usr/lib/libncursesw.so.6+0x2b187)
    #1 0x7ff1fe728ba1 in vwprintw (/usr/lib/libncursesw.so.6+0x24ba1)
    #2 0x7ff1fe728d34 in wprintw (/usr/lib/libncursesw.so.6+0x24d34)
    #3 0x5639f59939e5 in cw_nc_stats /home/mc/quarantedeux/corewar/src/nc/ui.c:76:2
    #4 0x5639f5993d12 in vm_guiupdate /home/mc/quarantedeux/corewar/src/nc/ui.c:92:2
    #5 0x5639f598db5d in vm_run /home/mc/quarantedeux/corewar/src/vm/run.c:50:8
    #6 0x5639f5988915 in main /home/mc/quarantedeux/corewar/src/vm/main.c:26:6
    #7 0x7ff1fd7e0f49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #8 0x5639f587f1e9 in _start (/home/mc/quarantedeux/corewar/corewar.san+0x311e9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/libncursesw.so.6+0x2b187) in _nc_printf_string_sp
==27669==ABORTING
```

**Comment by Freccia** [comment]
C'est bizarre moi j'ai pas ce segf sous linux...
T'est sur quelle architecture/os?

**Comment by JeanMax** [comment]
```
> uname -a
Linux nootnoot 4.15.12-1-ARCH #1 SMP PREEMPT Wed Mar 21 15:14:56 UTC 2018 x86_64 GNU/Linux
```

Par contre j'ai une *grosse* police, c'est surement liée à #3

**Comment by JeanMax** [comment]
c'etait bien a cause de la taille de la fenetre...
